int QVdeletepicture (int);
int QVtakepicture (void);
int QVgetpicture (int, uint8_t *, int, int, FILE *);
int QVmovepicture (int, int);
int QV4split (int *);
int QV9split (int *);
int QVprotect (int, int);
int QVhidepicnum ();
int QVpoweroff ();
int QVcolorpattern ();
int QVpicattr (int);
int QVgetsize2 (int);
int QVgetextdata (int, uint8_t *);
