int QVdeletepicture (int);
int QVtakepicture (void);
int QVgetpicture (int, uint8_t *, size_t, int, int, FILE *);
int QVmovepicture (int, int);
int QV4split (int *);
int QV9split (int *);
int QVprotect (int, int);
int QVhidepicnum (void);
int QVpoweroff (void);
int QVcolorpattern (void);
int QVpicattr (int);
int QVgetsize2 (int);
int QVgetextdata (int, uint8_t *, size_t);
