int	QVdeletepicture P__((int));
int	QVtakepicture P__((void));
int	QVgetpicture P__((int, u_char *, int, int, FILE *));
int	QVmovepicture P__((int, int));
int	QV4split P__((int *));
int	QV9split P__((int *));
int	QVprotect P__((int, int));
int	QVhidepicnum P__(());
int	QVpoweroff P__(());
int	QVcolorpattern P__(());
int	QVpicattr P__((int));
int	QVgetsize2 P__((int));
int	QVgetextdata P__((int, u_char *));
